version: '3.8'

services:
    clinica-app:
        image: nginx:latest
        ports:
            - "9080:80"
        working_dir: /app
        volumes:
            - ./devops/nginx/nginx_local.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
        depends_on:
            - php-fpm

    php-fpm:
        build:
            context: ./devops/php
        container_name: php-clinica
        working_dir: /app
        volumes:
            - ./app:/app
            - ./devops/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: clinica
            MYSQL_USER: clinica
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    # 🔧 Container adicional para build do frontend
    node:
        image: node:20
        container_name: node-clinica
        working_dir: /app
        volumes:
            - ./app:/app
        tty: true
        stdin_open: true

volumes:
    mysql_data:
