services:
  - type: web
    name: mtealife
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
      npm install
      npm run build
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://metalife.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: clinica-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: clinica-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: clinica-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: clinica-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: clinica-db
          property: password

databases:
  - name: clinica-db
    plan: free
    databaseName: clinica
    user: clinica
