services:
  - type: web
    name: metakids
    env: docker
    plan: free
    repo: https://github.com/luciofernandes/clinica
    dockerfilePath: ./Dockerfile
    disk:
      name: uploads
      mountPath: /app/storage/app/public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: clinica-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: clinica-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: clinica-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: clinica-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: clinica-db
          property: password

databases:
  - name: clinica-db
    plan: free
    databaseName: clinica
    user: clinica
